export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_FINANCES = 'SAVE_FINANCES';
export const CALCULATE_SAVINGS = 'CALCULATE_SAVINGS';
